version: "3.8"
services:
  postgres:
    image: postgres:13-buster
      - POSTGRES_USER=lkdm
      - POSTGRES_PASSWORD=yPVPuBjJ6yvGPyLegXGcsoxbFRNz
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"